Packaing fonts
deepin-community/fonts-lxgw-wenkai pull request #1
Opened 2023-07-03 06:37 UTC by xzy-bit

2023-07-04 01:30 UTC, xzl01 commented
需要修改commit信息以遵循约定式提交规范

2023-07-06 05:18 UTC, xzl01 requested changes
字体的二进制不存在，sources文件夹不应该被打包

2023-07-06 05:22 UTC, xzy-bit commented
对不起老师，刚刚push了错误版本的commit。在本地修改好了准备重新push上去的时候，git push -f又提示我443连接超时了，这几天老是这样子，有点不知道为什么&nbsp;


徐梓洋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月6日(星期四) 中午1:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deepin-community/fonts-lxgw-wenkai] feat: packaging and add fonts-lxgw-wenkai (PR #1)





 
@xzl01 requested changes on this pull request.
 
字体的二进制不存在，sources文件夹不应该被打包
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-07-07 03:36 UTC, xzy-bit commented
@chenchongbiao  去掉sources文件时发现OBS构建错误，查看日志发现是缺失sources文件夹。已加入二进制字体包。

2023-07-07 05:11 UTC, xzl01 requested changes
不要删除deepin文件夹

2023-07-07 05:17 UTC, xzy-bit commented
不好意思老师，今天上午机器又出问题了。终端和文件管理器都出现了问题，我在命令行做的所有操作，没注意到自己文件结构出了问题。重装完系统马上修改。
&nbsp;


徐梓洋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月7日(星期五) 中午1:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deepin-community/fonts-lxgw-wenkai] feat: packaging and add fonts-lxgw-wenkai (PR #1)





 
@xzl01 requested changes on this pull request.
 
不要删除deepin文件夹
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-07-11 02:01 UTC, chenchongbiao approved these changes

2023-07-11 02:15 UTC, xzl01 approved these changes

2023-07-11 02:16 UTC, merged